<a href="https://colab.research.google.com/github/KenObata/TISMIR_notebooks/blob/main/McNemarTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##This notebook runs McNemar tests to test the statistical significance of baseline models and transformer models.

Dataset: Top10 English songs only (=multi-class).
Split: StratifiedKfold.

In [1]:
import pandas as pd

McNemarDIRECTORY = '/content/drive/MyDrive/music4all/McNemar/'
TransformerDIRECTORY = '/content/drive/MyDrive/music4all/McNemar/transformer/'

from statsmodels.stats.contingency_tables import mcnemar

### Baseline Glove SVM vs. BERT base

In [ ]:
GloveSVM_split0_dim200 = pd.read_csv(McNemarDIRECTORY +'Baseline/GloveBaseline_SVM_split0_dim200.csv')
GloveSVM_split0_dim200 = GloveSVM_split0_dim200.drop(columns=['Unnamed: 0'])
GloveSVM_split0_dim200

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [ ]:
BERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_BERT_split0_fine_tune.csv')
BERT_split0_fine_tune = BERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
BERT_split0_fine_tune

          0
0     False
1     False
2     False
3      True
4     False
...     ...
2703  False
2704  False
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [ ]:
Baseline_SVMs=[GloveSVM_split0_dim200]
BERTs = [BERT_split0_fine_tune]

for Baseline_SVM, BERT in zip(Baseline_SVMs, BERTs):

  table = [[0, 0],
		     [0, 0]]
  for baseline, BERT_bool in zip(Baseline_SVM["0"], RoBERTa["0"]):
    if baseline==True and BERT_bool == True:
      table[0][0]+=1
    elif baseline==False and BERT_bool == True:
      table[1][0]+=1
    elif baseline==True and BERT_bool == False:
      table[0][1]+=1
    elif baseline==False and BERT_bool == False:
      table[1][1]+=1
  print(table)

  # calculate mcnemar test
  result = mcnemar(table, exact=True)
  # summarize the finding
  print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
  # interpret the p-value
  alpha = 0.05
  if result.pvalue > alpha:
    print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
  else:
    print('Different proportions of errors (reject H0)')
  print('-------------------------')

[[421, 330], [460, 1497]]
statistic=330.000, p-value=0.000004236630
Different proportions of errors (reject H0)
-------------------------

### Baseline Glove SVM vs. RoBERTa base

In [ ]:
GloveSVM_split0_dim200 = pd.read_csv(McNemarDIRECTORY +'Baseline/GloveBaseline_SVM_split0_dim200.csv')
GloveSVM_split0_dim200

      Unnamed: 0      0
0              0  False
1              1  False
2              2  False
3              3  False
4              4  False
...          ...    ...
2703        2703  False
2704        2704   True
2705        2705  False
2706        2706  False
2707        2707  False

[2708 rows x 2 columns]

In [ ]:
GloveSVM_split0_dim200 = GloveSVM_split0_dim200.drop(columns=['Unnamed: 0'])
GloveSVM_split0_dim200

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [ ]:
RoBERTa_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_RoBERTa_split0_fine_tuning.csv')
RoBERTa_split0_fine_tune

      Unnamed: 0      0
0              0  False
1              1  False
2              2  False
3              3  False
4              4  False
...          ...    ...
2703        2703  False
2704        2704   True
2705        2705  False
2706        2706  False
2707        2707  False

[2708 rows x 2 columns]

In [ ]:
RoBERTa_split0_fine_tune = RoBERTa_split0_fine_tune.drop(columns=['Unnamed: 0'])
RoBERTa_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [ ]:
Baseline_SVMs=[GloveSVM_split0_dim200]
RoBERTas = [RoBERTa_split0_fine_tune]

for Baseline_SVM, RoBERTa in zip(Baseline_SVMs, RoBERTas):

  table = [[0, 0],
		     [0, 0]]
  for baseline, RoBERTa_bool in zip(Baseline_SVM["0"], RoBERTa["0"]):
    if baseline==True and RoBERTa_bool == True:
      table[0][0]+=1
    elif baseline==False and RoBERTa_bool == True:
      table[1][0]+=1
    elif baseline==True and RoBERTa_bool == False:
      table[0][1]+=1
    elif baseline==False and RoBERTa_bool == False:
      table[1][1]+=1
  print(table)

  # calculate mcnemar test
  result = mcnemar(table, exact=True)
  # summarize the finding
  print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
  # interpret the p-value
  alpha = 0.05
  if result.pvalue > alpha:
    print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
  else:
    print('Different proportions of errors (reject H0)')
  print('-------------------------')

[[445, 306], [499, 1458]]
statistic=306.000, p-value=0.000000000011
Different proportions of errors (reject H0)
-------------------------

In [ ]:
RoBERTa_transfer_learning_acc=[
0.21715377119415202
,0.24024432769541795
,0.2506639438590469
,0.20580664952668526
,0.27158291265934137]
RoBERTa_transfer_learning_acc

[0.21715377119415202,
 0.24024432769541795,
 0.2506639438590469,
 0.20580664952668526,
 0.27158291265934137]

In [ ]:
sum(RoBERTa_transfer_learning_acc)/5

0.2370903209869287

### Baseline Glove SVM vs. ALBERT base

In [ ]:
GloveSVM_split0_dim200 = pd.read_csv(McNemarDIRECTORY +'Baseline/GloveBaseline_SVM_split0_dim200.csv')
GloveSVM_split0_dim200 = GloveSVM_split0_dim200.drop(columns=['Unnamed: 0'])
GloveSVM_split0_dim200

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [ ]:
ALBERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_ALBERT_base_split0_fine_tuning.csv')
ALBERT_split0_fine_tune = ALBERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
ALBERT_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703   True
2704  False
2705  False
2706  False
2707   True

[2708 rows x 1 columns]

In [ ]:
Baseline_SVMs=[GloveSVM_split0_dim200]
RoBERTas = [ALBERT_split0_fine_tune]

for Baseline_SVM, RoBERTa in zip(Baseline_SVMs, RoBERTas):

  table = [[0, 0],
		     [0, 0]]
  for baseline, RoBERTa_bool in zip(Baseline_SVM["0"], RoBERTa["0"]):
    if baseline==True and RoBERTa_bool == True:
      table[0][0]+=1
    elif baseline==False and RoBERTa_bool == True:
      table[1][0]+=1
    elif baseline==True and RoBERTa_bool == False:
      table[0][1]+=1
    elif baseline==False and RoBERTa_bool == False:
      table[1][1]+=1
  print(table)

  # calculate mcnemar test
  result = mcnemar(table, exact=True)
  # summarize the finding
  print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
  # interpret the p-value
  alpha = 0.05
  if result.pvalue > alpha:
    print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
  else:
    print('Different proportions of errors (reject H0)')
  print('-------------------------')

[[408, 343], [476, 1481]]
statistic=343.000, p-value=0.000003799498
Different proportions of errors (reject H0)
-------------------------

### Baseline Glove SVM vs. XLNet 256 tokens

In [2]:
GloveSVM_split0_dim200 = pd.read_csv(McNemarDIRECTORY +'Baseline/GloveBaseline_SVM_split0_dim200.csv')
GloveSVM_split0_dim200 = GloveSVM_split0_dim200.drop(columns=['Unnamed: 0'])
GloveSVM_split0_dim200

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [3]:
XLNet256_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_XLNet_256_batch_everywhere_fine_tune_dropout02.csv')
XLNet256_split0_fine_tune = XLNet256_split0_fine_tune.drop(columns=['Unnamed: 0'])
XLNet256_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [5]:
Baseline_SVMs=[GloveSVM_split0_dim200]
XLNets = [XLNet256_split0_fine_tune]

for Baseline_SVM, XLNet in zip(Baseline_SVMs, XLNets):

  table = [[0, 0],
		     [0, 0]]
  for baseline, XLNet_bool in zip(Baseline_SVM["0"], XLNet["0"]):
    if baseline==True and XLNet_bool == True:
      table[0][0]+=1
    elif baseline==False and XLNet_bool == True:
      table[1][0]+=1
    elif baseline==True and XLNet_bool == False:
      table[0][1]+=1
    elif baseline==False and XLNet_bool == False:
      table[1][1]+=1
  print(table)

  # calculate mcnemar test
  result = mcnemar(table, exact=True)
  # summarize the finding
  print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
  # interpret the p-value
  alpha = 0.05
  if result.pvalue > alpha:
    print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
  else:
    print('Different proportions of errors (reject H0)')
  print('-------------------------')

[[418, 333], [465, 1492]]
statistic=333.000, p-value=0.000003361814
Different proportions of errors (reject H0)
-------------------------

### RoBERTa vs BERT

In [6]:
BERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_BERT_split0_fine_tune.csv')
BERT_split0_fine_tune = BERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
BERT_split0_fine_tune

          0
0     False
1     False
2     False
3      True
4     False
...     ...
2703  False
2704  False
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [7]:
RoBERTa_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_RoBERTa_split0_fine_tuning.csv')
RoBERTa_split0_fine_tune = RoBERTa_split0_fine_tune.drop(columns=['Unnamed: 0'])
RoBERTa_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [8]:
table = [[0, 0],
           [0, 0]]
for BERT_bool, RoBERTa_bool in zip(BERT_split0_fine_tune["0"], RoBERTa_split0_fine_tune["0"]):
  if BERT_bool==True and RoBERTa_bool == True:
    table[0][0]+=1
  elif BERT_bool==False and RoBERTa_bool == True:
    table[1][0]+=1
  elif BERT_bool==True and RoBERTa_bool == False:
    table[0][1]+=1
  elif BERT_bool==False and RoBERTa_bool == False:
    table[1][1]+=1
print(table)

# calculate mcnemar test
result = mcnemar(table, exact=True)
# summarize the finding
print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
# interpret the p-value
alpha = 0.05
if result.pvalue > alpha:
  print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
else:
  print('Different proportions of errors (reject H0)')
print('-------------------------')

[[599, 282], [345, 1482]]
statistic=282.000, p-value=0.013221909883
Different proportions of errors (reject H0)
-------------------------

### ALBERT vs BERT

In [12]:
BERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_BERT_split0_fine_tune.csv')
BERT_split0_fine_tune = BERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
BERT_split0_fine_tune

          0
0     False
1     False
2     False
3      True
4     False
...     ...
2703  False
2704  False
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [13]:
ALBERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_ALBERT_base_split0_fine_tuning.csv')
ALBERT_split0_fine_tune = ALBERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
ALBERT_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703   True
2704  False
2705  False
2706  False
2707   True

[2708 rows x 1 columns]

In [14]:
table = [[0, 0],
           [0, 0]]
for BERT_bool, ALBERT_bool in zip(BERT_split0_fine_tune["0"], ALBERT_split0_fine_tune["0"]):
  if BERT_bool==True and ALBERT_bool == True:
    table[0][0]+=1
  elif BERT_bool==False and ALBERT_bool == True:
    table[1][0]+=1
  elif BERT_bool==True and ALBERT_bool == False:
    table[0][1]+=1
  elif BERT_bool==False and ALBERT_bool == False:
    table[1][1]+=1
print(table)

# calculate mcnemar test
result = mcnemar(table, exact=True)
# summarize the finding
print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
# interpret the p-value
alpha = 0.05
if result.pvalue > alpha:
  print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
else:
  print('Different proportions of errors (reject H0)')
print('-------------------------')

[[518, 363], [366, 1461]]
statistic=363.000, p-value=0.940958158284
Same proportions of errors (fail to reject H0).
 there is no statistically significant difference in the disagreements between the two models.
-------------------------

### XLNet vs BERT

In [9]:
BERT_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_BERT_split0_fine_tune.csv')
BERT_split0_fine_tune = BERT_split0_fine_tune.drop(columns=['Unnamed: 0'])
BERT_split0_fine_tune

          0
0     False
1     False
2     False
3      True
4     False
...     ...
2703  False
2704  False
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [10]:
XLNet256_split0_fine_tune = pd.read_csv(TransformerDIRECTORY +'McNemar_XLNet_256_batch_everywhere_fine_tune_dropout02.csv')
XLNet256_split0_fine_tune = XLNet256_split0_fine_tune.drop(columns=['Unnamed: 0'])
XLNet256_split0_fine_tune

          0
0     False
1     False
2     False
3     False
4     False
...     ...
2703  False
2704   True
2705  False
2706  False
2707  False

[2708 rows x 1 columns]

In [11]:
table = [[0, 0],
           [0, 0]]
for BERT_bool, XLNet_bool in zip(BERT_split0_fine_tune["0"], XLNet256_split0_fine_tune["0"]):
  if BERT_bool==True and XLNet_bool == True:
    table[0][0]+=1
  elif BERT_bool==False and XLNet_bool == True:
    table[1][0]+=1
  elif BERT_bool==True and XLNet_bool == False:
    table[0][1]+=1
  elif BERT_bool==False and XLNet_bool == False:
    table[1][1]+=1
print(table)

# calculate mcnemar test
result = mcnemar(table, exact=True)
# summarize the finding
print('statistic=%.3f, p-value=%.12f' % (result.statistic, result.pvalue))
# interpret the p-value
alpha = 0.05
if result.pvalue > alpha:
  print('Same proportions of errors (fail to reject H0).\n there is no statistically significant difference in the disagreements between the two models.')
else:
  print('Different proportions of errors (reject H0)')
print('-------------------------')

[[553, 328], [330, 1497]]
statistic=328.000, p-value=0.968907037058
Same proportions of errors (fail to reject H0).
 there is no statistically significant difference in the disagreements between the two models.
-------------------------